# Generated by Django 2.2.6 on 2019-12-11 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='产品名称', max_length=50)),
                ('introduction', models.TextField(default='产品介绍')),
                ('product_linked', models.CharField(default='http://', max_length=100)),
                ('icon', models.ImageField(default='xixi.png', upload_to='image/')),
                ('picture', models.ImageField(default='lys.jpg', upload_to='image/')),
                ('product_date', models.DateField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
