# Generated by Django 2.2.6 on 2019-12-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(default='xixi.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='xixi.jpg', upload_to='images/'),
        ),
    ]
